### ISSUE TITLE
Typo under 4. "Geometrische Verteilung"

### ISSUE THREAD

**Issue by chrisonntag** [lordreif/stochastik#1]
Chapter 4 states 

`Gedächtnislos: ∀k1,k2 ∈ N mit k1 < k2 : P({X > k2} | {X > k2}) = P({X > k2 − k1})`

which should be 

`Gedächtnislos: ∀k1,k2 ∈ N mit k1 < k2 : P({X > k2} | {X > k1}) = P({X > k2 − k1})`

**Comment by lordreif** [comment]
done, thanks
